### ISSUE TITLE
Traceback (most recent call last):   File "weibo.py", line 8, in <module>     import urllib2 ImportError: No module named 'urllib2'

### ISSUE THREAD

**Issue by JremeryHe** [dingmyu/weibo_analysis#4]
Traceback (most recent call last):
  File "weibo.py", line 8, in <module>
    import urllib2
ImportError: No module named 'urllib2'

**Comment by PpoiOI** [comment]
应该是你python的版本问题，我用python3跑也有这个问题 。在python3.3里面，用urllib.request代替urllib2就可以了
